export type DemoProductSeed = {
  name: string;
  slug: string;
  description: string;
  price: number;
  imageUrl: string;
  stockQuantity: number;
};

export const DEMO_PRODUCTS: DemoProductSeed[] = [
  {
    name: "Wireless Earbuds",
    slug: "wireless-earbuds",
    description: "Compact true wireless earbuds with charging case and clear call quality.",
    price: 24.9,
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop",
    stockQuantity: 48,
  },
  {
    name: "Bluetooth Speaker",
    slug: "bluetooth-speaker",
    description: "Portable waterproof speaker with 12-hour battery life.",
    price: 39.5,
    imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop",
    stockQuantity: 32,
  },
  {
    name: "USB-C Charger",
    slug: "usb-c-charger",
    description: "65W fast charger with dual USB-C ports for phones and laptops.",
    price: 14.75,
    imageUrl: "https://images.unsplash.com/photo-1583863788433-e58f8b8b4f6f?w=600&auto=format&fit=crop",
    stockQuantity: 80,
  },
  {
    name: "Gaming Mouse",
    slug: "gaming-mouse",
    description: "Ergonomic RGB gaming mouse with adjustable DPI.",
    price: 18.9,
    imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop",
    stockQuantity: 44,
  },
  {
    name: "Mechanical Keyboard",
    slug: "mechanical-keyboard",
    description: "Compact mechanical keyboard with tactile switches.",
    price: 49.9,
    imageUrl: "https://images.unsplash.com/photo-1511467591282-7a90ca295994?w=600&auto=format&fit=crop",
    stockQuantity: 20,
  },
  {
    name: "Phone Case",
    slug: "phone-case",
    description: "Shock-absorbing clear case with raised camera protection.",
    price: 8.5,
    imageUrl: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&auto=format&fit=crop",
    stockQuantity: 120,
  },
  {
    name: "Power Bank",
    slug: "power-bank",
    description: "10,000mAh slim power bank with USB-C input and output.",
    price: 16.25,
    imageUrl: "https://images.unsplash.com/photo-1609091839311-9ed1aeb48f1c?w=600&auto=format&fit=crop",
    stockQuantity: 56,
  },
  {
    name: "Smart Watch",
    slug: "smart-watch",
    description: "Fitness smartwatch with heart-rate tracking and notifications.",
    price: 59.9,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
    stockQuantity: 18,
  },
  {
    name: "Laptop Stand",
    slug: "laptop-stand",
    description: "Aluminium adjustable stand for better posture and cooling.",
    price: 21.5,
    imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop",
    stockQuantity: 28,
  },
  {
    name: "HDMI Cable",
    slug: "hdmi-cable",
    description: "2m braided HDMI 2.0 cable for TVs and monitors.",
    price: 6.9,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop",
    stockQuantity: 95,
  },
  {
    name: "Webcam",
    slug: "webcam",
    description: "1080p webcam with built-in microphone for meetings.",
    price: 27.5,
    imageUrl: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=600&auto=format&fit=crop",
    stockQuantity: 24,
  },
  {
    name: "Wireless Charger",
    slug: "wireless-charger",
    description: "15W Qi wireless charging pad with LED indicator.",
    price: 12.9,
    imageUrl: "https://images.unsplash.com/photo-1591290619762-d2b4a1e3f2cc?w=600&auto=format&fit=crop",
    stockQuantity: 40,
  },
  {
    name: "Tablet Stand",
    slug: "tablet-stand",
    description: "Foldable tablet and phone stand for desk or kitchen use.",
    price: 9.75,
    imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&fit=crop",
    stockQuantity: 60,
  },
  {
    name: "Noise Cancelling Headphones",
    slug: "noise-cancelling-headphones",
    description: "Over-ear headphones with active noise cancellation.",
    price: 74.9,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop",
    stockQuantity: 15,
  },
  {
    name: "USB Hub",
    slug: "usb-hub",
    description: "4-port USB 3.0 hub for laptops and desktops.",
    price: 11.4,
    imageUrl: "https://images.unsplash.com/photo-1625948515291-69613efd202f?w=600&auto=format&fit=crop",
    stockQuantity: 36,
  },
  {
    name: "Portable SSD",
    slug: "portable-ssd",
    description: "500GB portable SSD with USB-C connectivity.",
    price: 42.5,
    imageUrl: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&auto=format&fit=crop",
    stockQuantity: 22,
  },
  {
    name: "Smart Plug",
    slug: "smart-plug",
    description: "Wi-Fi smart plug with scheduling and energy monitoring.",
    price: 10.9,
    imageUrl: "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop",
    stockQuantity: 50,
  },
  {
    name: "Ring Light",
    slug: "ring-light",
    description: "10-inch LED ring light with tripod for content creators.",
    price: 22.9,
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop",
    stockQuantity: 19,
  },
  {
    name: "Action Camera",
    slug: "action-camera",
    description: "4K action camera with waterproof housing.",
    price: 89.9,
    imageUrl: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop",
    stockQuantity: 12,
  },
  {
    name: "Fitness Tracker",
    slug: "fitness-tracker",
    description: "Lightweight fitness band with sleep and step tracking.",
    price: 19.9,
    imageUrl: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop",
    stockQuantity: 34,
  },
  {
    name: "Car Phone Mount",
    slug: "car-phone-mount",
    description: "Magnetic dashboard mount for safe navigation.",
    price: 7.5,
    imageUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&auto=format&fit=crop",
    stockQuantity: 70,
  },
  {
    name: "Screen Protector",
    slug: "screen-protector",
    description: "Tempered glass screen protector with easy install kit.",
    price: 5.9,
    imageUrl: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&auto=format&fit=crop",
    stockQuantity: 150,
  },
  {
    name: "Mini Projector",
    slug: "mini-projector",
    description: "Portable projector for movies and presentations.",
    price: 95.5,
    imageUrl: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&auto=format&fit=crop",
    stockQuantity: 8,
  },
  {
    name: "Smart Doorbell",
    slug: "smart-doorbell",
    description: "Wi-Fi doorbell camera with two-way audio.",
    price: 68.9,
    imageUrl: "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop",
    stockQuantity: 10,
  },
  {
    name: "VR Headset",
    slug: "vr-headset",
    description: "Standalone VR headset for games and immersive video.",
    price: 129.9,
    imageUrl: "https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=600&auto=format&fit=crop",
    stockQuantity: 6,
  },
];

export const DEMO_ORDER_STATUS_SAMPLES = [
  "delivered",
  "delivered",
  "delivered",
  "preparing",
  "out_for_delivery",
  "pending",
  "confirmed",
] as const;
