export const DEFAULT_SETTINGS = [
  {
    key: "currency",
    value: "BHD",
    type: "string",
    group: "general",
    label: "Currency",
    isPublic: true,
    isEditable: true,
  },
  {
    key: "tax_percentage",
    value: 0,
    type: "number",
    group: "payments",
    label: "Tax Percentage",
    isPublic: true,
    isEditable: true,
  },
  {
    key: "default_delivery_fee",
    value: 1.5,
    type: "number",
    group: "delivery",
    label: "Default Delivery Fee",
    isPublic: true,
    isEditable: true,
  },
  {
    key: "platform_commission_percentage",
    value: 10,
    type: "number",
    group: "payments",
    label: "Platform Commission Percentage",
    isPublic: false,
    isEditable: true,
  },
  {
    key: "order_statuses",
    value: ["pending", "confirmed", "preparing", "out_for_delivery", "delivered", "cancelled"],
    type: "array",
    group: "orders",
    label: "Order Statuses",
    isPublic: true,
    isEditable: true,
  },
  {
    key: "payment_statuses",
    value: ["pending", "paid", "failed", "refunded"],
    type: "array",
    group: "payments",
    label: "Payment Statuses",
    isPublic: true,
    isEditable: true,
  },
  {
    key: "store_approval_required",
    value: true,
    type: "boolean",
    group: "stores",
    label: "Store Approval Required",
    isPublic: false,
    isEditable: true,
  },
  {
    key: "maintenance_mode",
    value: false,
    type: "boolean",
    group: "system",
    label: "Maintenance Mode",
    isPublic: true,
    isEditable: true,
  },
  {
    key: "default_order_status",
    value: "pending",
    type: "string",
    group: "orders",
    label: "Default Order Status",
    isPublic: true,
    isEditable: true,
  },
  {
    key: "default_payment_status",
    value: "pending",
    type: "string",
    group: "payments",
    label: "Default Payment Status",
    isPublic: true,
    isEditable: true,
  },
  {
    key: "payment_provider",
    value: "mock",
    type: "string",
    group: "payments",
    label: "Payment Provider",
    isPublic: true,
    isEditable: true,
  },
  {
    key: "minimum_order_amount",
    value: 0,
    type: "number",
    group: "orders",
    label: "Minimum Order Amount",
    isPublic: true,
    isEditable: true,
  },
  {
    key: "max_cart_items",
    value: 50,
    type: "number",
    group: "orders",
    label: "Maximum Cart Items",
    isPublic: true,
    isEditable: true,
  },
  {
    key: "store_auto_approval",
    value: false,
    type: "boolean",
    group: "stores",
    label: "Store Auto Approval",
    isPublic: false,
    isEditable: true,
  },
  {
    key: "mock_payments_enabled",
    value: true,
    type: "boolean",
    group: "payments",
    label: "Mock Payments Enabled",
    isPublic: false,
    isEditable: true,
  },
] as const;

export type DefaultSetting = (typeof DEFAULT_SETTINGS)[number];
export type SettingKey = DefaultSetting["key"];
/** Matches `settings.type` in schema (includes `json` for future settings). */
export type SettingType = DefaultSetting["type"] | "json";
export type SettingGroup = DefaultSetting["group"];
